sudo: required

language: generic

env:
  global:
  - secure: A8i1jK9oTVgOCyQJQ9Hjk8c2hium9NEKL8cmkNBvVoUUniut6iE+GkzvDX5BxTOSoBtrRyKAtGcG7TF34AiBZ7H6UuXMBnK5ulLyg0rN5WH1zzZSFtI5mb8FtXIpCZA//t2V0ez9hXHr1vZxoY2D+sApgGoblSTpvTIH3jMlpcGMGxQkl/PmUSKLXhqrOtSbkLr3Gc/rvBpWTvjFXejordCe7zVHkOYj7QdkqODLtv4tXvOBnuSXD/t9F3f9KQ4wudtYwhW1HNziq/5E1Csd+8kQSWq+jsohDrxiYIVUJmM11wJ8ykagIT1nCG5KYRKazNj7oKBio7B19SbacwbtzrBwY/kLE2UBLxqLa9KT9v64UdOOt6NXB9snfgKOpVi9Q2hyStxm/PevPJfesRIK+7H09GVIHjFaXzfTtCSSE5Gp2guo5J13v8+TMEcefTqX4knFkNUF10gDeJJri7Wq8wG/5dyWQ4hGgELg8h+iPs6JyQluSAvdcmKCzAsdWuS1tNkZEgB7tKdlvtlt9dxQKBiLrDmBgxafqJswDSq12Co1TEAGHk4/eYg4EIl2/R8dDwBNNIfe8M+PIrS+WS27c/j4Sla24wJBQbBzjLJlUyHj2XlNCF7aTjmMrk1LE51rRqLPOkCEIXMrrK9YJyK4fXb3rXMCn9mrEXdk/79bTPU=
  - secure: ZcZekc40fOxsKfJuMHMmiR0Deun+X01tE5C5e1ifCxhHIx7Ly1UVtGAMHWd7Fj6SjxblXue/Fcth0qZ323wjQdXz0PiU2npyKl2nYwXJBxU4LyHolV4KbNsJbQV9Bj5GSXyIozSU6MYvIcSTR9wzjGNZWUQqxTS1JTTAhjzVrGkXOIaEGyiwcUiBGnH8lHjGs6OftgF/qZY4WqSRr/TbSsA5UfHtvLbuDBfsxgm7SNAaOqPNmjR4j0UFF+5Ue2+XLhxYbGy86WBuTEzIrv6jWjN0v41NaSpOiYlHEM86MDZwsqGSayjQOUjUFP7WmqHYMcLu54X7zCGV7e2T5y9e3PJBsYu9t43VfFz6NdxPdOfga5njiWaHt2bUzgZCsTI4jkHklJbDtVR2+R5XAwdq+cIVCIDYA9H3cAt+QSd76fsrG9giM8o0sSs4tgvXdiMQrOaBrYCsXkPOaAVmr8fRkvV48m4ccuXhOYQyepmSAZAyD3OZY53NRQx71hDuaJf52wywV2J6HhZuICWDQ3+x4RxcemZtLziokgr3xSu+A8m0nhMSD9JcFMjIIUEJL2bK7TpGmUPz2dZXRscsrodZi2mo8uifgT+g42OHp3OLkibJTUuirhdUyK1QmQHWA8CoP6mlpwBDRWKU+bXBZQEAiHuGyTSxMyiAGCZ4A1ZVEBo=

services:
  - docker

script:
  - ./bin/build

after_success:
  - ./bin/push
